# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.22]
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: DB Init
      run: docker compose up -d postgres

    - name: Lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.0
        args: controllers/ database/ models/ routes/
    - name: Test
      run: DB_HOST=${{secrets.DB_HOST}} DB_PASSWORD=${{secrets.DB_PASSWORD}} DB_NAME=${{secrets.DB_NAME}} DB_USER=${{secrets.DB_USER}} DB_PORT=${{secrets.DB_PORT}} go test -v main_test.go
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    steps:
      - name: Build
        run: go build main.go